2012/05/26 23:43:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "controllers/admin"' in /var/www/yii/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('')
#1 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/taller/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller/index.php
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/05/26 23:44:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "controllers/AddressController"' in /var/www/yii/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('')
#1 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/taller/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller/index.php
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/08 15:40:14 [error] [exception.CException] exception 'CException' with message 'Alias "application.extensions.mbmenu.MbMenu" is invalid. Make sure it points to an existing PHP file.' in /var/www/yii/framework/YiiBase.php:318
Stack trace:
#0 /var/www/yii/framework/web/CWidgetFactory.php(147): YiiBase::import('application.ext...', true)
#1 /var/www/yii/framework/web/CBaseController.php(147): CWidgetFactory->createWidget(Object(SiteController), 'application.ext...', Array)
#2 /var/www/yii/framework/web/CBaseController.php(173): CBaseController->createWidget('application.ext...', Array)
#3 /var/www/taller/themes/shadow_dancer/views/layouts/main.php(61): CBaseController->widget('application.ext...', Array)
#4 /var/www/yii/framework/web/CBaseController.php(127): require('/var/www/taller...')
#5 /var/www/yii/framework/web/CBaseController.php(96): CBaseController->renderInternal('/var/www/taller...', Array, true)
#6 /var/www/yii/framework/web/widgets/CContentDecorator.php(77): CBaseController->renderFile('/var/www/taller...', Array, true)
#7 /var/www/yii/framework/web/widgets/CContentDecorator.php(55): CContentDecorator->decorate('<div class="con...')
#8 /var/www/yii/framework/web/widgets/COutputProcessor.php(45): CContentDecorator->processOutput('<div class="con...')
#9 /var/www/yii/framework/web/CBaseController.php(207): COutputProcessor->run()
#10 /var/www/yii/framework/web/CBaseController.php(301): CBaseController->endWidget('CContentDecorat...')
#11 /var/www/taller/themes/shadow_dancer/views/layouts/column1.php(7): CBaseController->endContent()
#12 /var/www/yii/framework/web/CBaseController.php(127): require('/var/www/taller...')
#13 /var/www/yii/framework/web/CBaseController.php(96): CBaseController->renderInternal('/var/www/taller...', Array, true)
#14 /var/www/yii/framework/web/CController.php(785): CBaseController->renderFile('/var/www/taller...', Array, true)
#15 /var/www/taller/protected/controllers/SiteController.php(32): CController->render('index')
#16 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionIndex()
#17 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#18 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#19 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('index')
#21 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/index')
#22 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#23 /var/www/taller/index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/taller/index.php?r=site/index
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/08 16:09:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "phone" solicitada.' in /var/www/yii/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii/framework/web/CController.php(271): CController->missingAction('phone')
#1 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('phone')
#2 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/phone')
#3 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/taller/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller/index.php?r=site/phone
---
2012/06/08 16:10:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "phone" solicitada.' in /var/www/yii/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii/framework/web/CController.php(271): CController->missingAction('phone')
#1 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('phone')
#2 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/phone')
#3 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/taller/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller/index.php?r=site/phone
---
2012/06/08 16:12:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php?r=site/page&view=buttons_and_icons
---
2012/06/08 16:13:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "contact"' in /var/www/yii/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('contact')
#1 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/taller/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller/index.php?r=contact
---
2012/06/08 16:15:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "adress/create"' in /var/www/yii/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('adress/create')
#1 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/taller/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller/index.php?r=adress/create
---
2012/06/08 17:07:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "GII"' in /var/www/yii/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('GII')
#1 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/taller/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller/index.php?r=GII
---
2012/06/08 17:13:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /var/www/yii/framework/web/auth/CAccessControlFilter.php:157
Stack trace:
#0 /var/www/yii/framework/web/auth/CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /var/www/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /var/www/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('admin')
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('person/admin')
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/taller/index.php?r=person/admin
HTTP_REFERER=http://localhost/taller/index.php?r=person/create
---
2012/06/08 17:22:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php/site/contact
---
2012/06/08 17:25:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:26:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:28:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:29:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:31:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:33:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:34:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:35:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:35:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:36:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:37:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:40:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:45:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:45:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:46:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:46:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:50:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 17:56:52 [error] [php] Missing argument 2 for CActiveForm::labelEx(), called in /var/www/taller/themes/shadow_dancer/views/site/login.php on line 24 and defined (/var/www/yii/framework/web/widgets/CActiveForm.php:558)
Stack trace:
#0 /var/www/yii/framework/web/CBaseController.php(96): SiteController->renderInternal()
#1 /var/www/yii/framework/web/CController.php(870): SiteController->renderFile()
#2 /var/www/yii/framework/web/CController.php(783): SiteController->renderPartial()
#3 /var/www/taller/protected/controllers/SiteController.php(92): SiteController->render()
#4 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#5 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#6 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#7 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#8 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#9 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#10 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/themes/shadow_dancer/views/site/login.php (24)
in /var/www/taller/protected/controllers/SiteController.php (92)
in /var/www/taller/index.php (13)
2012/06/08 18:24:57 [error] [exception.CException] exception 'CException' with message 'Propiedad "Person"."username" no se encuentra definida.' in /var/www/yii/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(144): CComponent->__get('username')
#1 /var/www/taller/protected/components/UserIdentity.php(40): CActiveRecord->__get('username')
#2 /var/www/taller/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/yii/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/taller/protected/controllers/SiteController.php(88): CModel->validate()
#7 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#8 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#9 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#10 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('login')
#12 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/login')
#13 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#14 /var/www/taller/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/taller/index.php?r=site/login
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/08 18:27:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 18:27:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 18:27:42 [error] [php] Trying to get property of non-object (/var/www/taller/protected/components/UserIdentity.php:25)
Stack trace:
#0 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute()
#1 /var/www/yii/framework/base/CModel.php(158): CInlineValidator->validate()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->validate()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/components/UserIdentity.php (25)
in /var/www/taller/protected/models/LoginForm.php (52)
in /var/www/taller/protected/controllers/SiteController.php (88)
2012/06/08 18:28:36 [error] [php] Trying to get property of non-object (/var/www/taller/protected/components/UserIdentity.php:26)
Stack trace:
#0 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute()
#1 /var/www/yii/framework/base/CModel.php(158): CInlineValidator->validate()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->validate()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/components/UserIdentity.php (26)
in /var/www/taller/protected/models/LoginForm.php (52)
in /var/www/taller/protected/controllers/SiteController.php (88)
2012/06/08 18:28:44 [error] [php] Trying to get property of non-object (/var/www/taller/protected/components/UserIdentity.php:26)
Stack trace:
#0 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute()
#1 /var/www/yii/framework/base/CModel.php(158): CInlineValidator->validate()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->validate()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/components/UserIdentity.php (26)
in /var/www/taller/protected/models/LoginForm.php (52)
in /var/www/taller/protected/controllers/SiteController.php (88)
2012/06/08 18:29:11 [error] [php] Trying to get property of non-object (/var/www/taller/protected/components/UserIdentity.php:26)
Stack trace:
#0 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute()
#1 /var/www/yii/framework/base/CModel.php(158): CInlineValidator->validate()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->validate()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/components/UserIdentity.php (26)
in /var/www/taller/protected/models/LoginForm.php (52)
in /var/www/taller/protected/controllers/SiteController.php (88)
2012/06/08 18:54:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 19:03:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 19:21:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 19:22:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/08 19:31:38 [error] [php] Undefined variable: model (/var/www/taller/themes/shadow_dancer/views/site/index.php:25)
Stack trace:
#0 /var/www/yii/framework/web/CController.php(870): SiteController->renderFile()
#1 /var/www/yii/framework/web/CController.php(783): SiteController->renderPartial()
#2 /var/www/taller/protected/controllers/SiteController.php(32): SiteController->render()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionIndex()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php
in /var/www/taller/themes/shadow_dancer/views/site/index.php (25)
in /var/www/taller/protected/controllers/SiteController.php (32)
in /var/www/taller/index.php (13)
2012/06/08 19:34:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php?r=site/page&view=graphs
---
2012/06/08 19:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "gg" solicitada.' in /var/www/yii/framework/web/CController.php:484
Stack trace:
#0 /var/www/yii/framework/web/CController.php(271): CController->missingAction('gg')
#1 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('gg')
#2 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/gg')
#3 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /var/www/taller/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller/index.php?r=site/gg
---
2012/06/08 20:04:47 [error] [php] Undefined variable: _SESSION (/var/www/taller/themes/shadow_dancer/views/layouts/main.php:29)
Stack trace:
#0 /var/www/yii/framework/web/widgets/CContentDecorator.php(77): SiteController->renderFile()
#1 /var/www/yii/framework/web/widgets/CContentDecorator.php(55): CContentDecorator->decorate()
#2 /var/www/yii/framework/web/widgets/COutputProcessor.php(45): CContentDecorator->processOutput()
#3 /var/www/yii/framework/web/CBaseController.php(207): CContentDecorator->run()
#4 /var/www/yii/framework/web/CBaseController.php(301): SiteController->endWidget()
#5 /var/www/taller/themes/shadow_dancer/views/layouts/column1.php(7): SiteController->endContent()
#6 /var/www/yii/framework/web/CBaseController.php(127): require()
#7 /var/www/yii/framework/web/CBaseController.php(96): SiteController->renderInternal()
#8 /var/www/yii/framework/web/CController.php(785): SiteController->renderFile()
#9 /var/www/taller/protected/controllers/SiteController.php(32): SiteController->render()
#10 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionIndex()
#11 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#12 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#13 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#14 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#15 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#16 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#17 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php
in /var/www/taller/themes/shadow_dancer/views/layouts/main.php (29)
in /var/www/taller/themes/shadow_dancer/views/layouts/column1.php (7)
in /var/www/taller/protected/controllers/SiteController.php (32)
2012/06/08 20:05:11 [error] [php] Undefined variable: _SESSION (/var/www/taller/themes/shadow_dancer/views/layouts/main.php:29)
Stack trace:
#0 /var/www/yii/framework/web/widgets/CContentDecorator.php(77): SiteController->renderFile()
#1 /var/www/yii/framework/web/widgets/CContentDecorator.php(55): CContentDecorator->decorate()
#2 /var/www/yii/framework/web/widgets/COutputProcessor.php(45): CContentDecorator->processOutput()
#3 /var/www/yii/framework/web/CBaseController.php(207): CContentDecorator->run()
#4 /var/www/yii/framework/web/CBaseController.php(301): SiteController->endWidget()
#5 /var/www/taller/themes/shadow_dancer/views/layouts/column1.php(7): SiteController->endContent()
#6 /var/www/yii/framework/web/CBaseController.php(127): require()
#7 /var/www/yii/framework/web/CBaseController.php(96): SiteController->renderInternal()
#8 /var/www/yii/framework/web/CController.php(785): SiteController->renderFile()
#9 /var/www/taller/protected/controllers/SiteController.php(32): SiteController->render()
#10 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionIndex()
#11 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#12 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#13 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#14 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#15 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#16 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#17 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php
in /var/www/taller/themes/shadow_dancer/views/layouts/main.php (29)
in /var/www/taller/themes/shadow_dancer/views/layouts/column1.php (7)
in /var/www/taller/protected/controllers/SiteController.php (32)
2012/06/08 20:06:23 [error] [php] Undefined variable: _SESSION (/var/www/taller/themes/shadow_dancer/views/site/index.php:2)
Stack trace:
#0 /var/www/yii/framework/web/CController.php(870): SiteController->renderFile()
#1 /var/www/yii/framework/web/CController.php(783): SiteController->renderPartial()
#2 /var/www/taller/protected/controllers/SiteController.php(32): SiteController->render()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionIndex()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/index
in /var/www/taller/themes/shadow_dancer/views/site/index.php (2)
in /var/www/taller/protected/controllers/SiteController.php (32)
in /var/www/taller/index.php (13)
2012/06/08 22:06:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php?r=site/index
---
2012/06/08 22:08:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php?r=site/page&view=Demo+404+page
---
2012/06/08 22:55:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 pagejhj" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 pagejh...')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+pagejhj
---
2012/06/08 22:55:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "jkjkjk" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('jkjkjk')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=jkjkjk
---
2012/06/08 22:55:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "shhjhjg"' in /var/www/yii/framework/web/CWebApplication.php:280
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('shhjhjg')
#1 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /var/www/taller/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller/index.php?r=shhjhjg
---
2012/06/08 23:23:11 [error] [php] Trying to get property of non-object (/var/www/taller/protected/components/UserIdentity.php:48)
Stack trace:
#0 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate()
#1 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute()
#2 /var/www/yii/framework/base/CModel.php(158): CInlineValidator->validate()
#3 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->validate()
#4 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#5 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#6 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#7 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#8 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#9 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#10 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/components/UserIdentity.php (48)
in /var/www/taller/protected/components/UserIdentity.php (34)
in /var/www/taller/protected/models/LoginForm.php (52)
2012/06/08 23:36:00 [error] [php] session_regenerate_id(): Cannot regenerate session id - headers already sent (/var/www/yii/framework/web/CHttpSession.php:182)
Stack trace:
#0 /var/www/yii/framework/web/auth/CWebUser.php(228): CWebUser->changeIdentity()
#1 /var/www/taller/protected/models/LoginForm.php(71): CWebUser->login()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->login()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/models/LoginForm.php (71)
in /var/www/taller/protected/controllers/SiteController.php (88)
in /var/www/taller/index.php (13)
2012/06/08 23:37:03 [error] [php] session_regenerate_id(): Cannot regenerate session id - headers already sent (/var/www/yii/framework/web/CHttpSession.php:182)
Stack trace:
#0 /var/www/yii/framework/web/auth/CWebUser.php(228): CWebUser->changeIdentity()
#1 /var/www/taller/protected/models/LoginForm.php(71): CWebUser->login()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->login()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/models/LoginForm.php (71)
in /var/www/taller/protected/controllers/SiteController.php (88)
in /var/www/taller/index.php (13)
2012/06/08 23:41:47 [error] [exception.CException] exception 'CException' with message 'Propiedad "User"."relations" no se encuentra definida.' in /var/www/yii/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(144): CComponent->__get('relations')
#1 /var/www/taller/protected/components/UserIdentity.php(44): CActiveRecord->__get('relations')
#2 /var/www/taller/protected/components/UserIdentity.php(35): UserIdentity->getDatos(Object(User))
#3 /var/www/taller/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#5 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /var/www/yii/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#7 /var/www/taller/protected/controllers/SiteController.php(88): CModel->validate()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#9 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('login')
#13 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/login')
#14 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/taller/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/taller/index.php?r=site/login
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/08 23:42:14 [error] [php] session_regenerate_id(): Cannot regenerate session id - headers already sent (/var/www/yii/framework/web/CHttpSession.php:182)
Stack trace:
#0 /var/www/yii/framework/web/auth/CWebUser.php(228): CWebUser->changeIdentity()
#1 /var/www/taller/protected/models/LoginForm.php(71): CWebUser->login()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->login()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/models/LoginForm.php (71)
in /var/www/taller/protected/controllers/SiteController.php (88)
in /var/www/taller/index.php (13)
2012/06/08 23:44:45 [error] [php] Trying to get property of non-object (/var/www/taller/protected/components/UserIdentity.php:44)
Stack trace:
#0 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate()
#1 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute()
#2 /var/www/yii/framework/base/CModel.php(158): CInlineValidator->validate()
#3 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->validate()
#4 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#5 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#6 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#7 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#8 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#9 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#10 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/components/UserIdentity.php (44)
in /var/www/taller/protected/components/UserIdentity.php (35)
in /var/www/taller/protected/models/LoginForm.php (52)
2012/06/08 23:45:17 [error] [php] Undefined index: state (/var/www/taller/protected/components/UserIdentity.php:44)
Stack trace:
#0 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate()
#1 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute()
#2 /var/www/yii/framework/base/CModel.php(158): CInlineValidator->validate()
#3 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->validate()
#4 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#5 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#6 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#7 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#8 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#9 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#10 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/components/UserIdentity.php (44)
in /var/www/taller/protected/components/UserIdentity.php (35)
in /var/www/taller/protected/models/LoginForm.php (52)
2012/06/08 23:45:28 [error] [php] session_regenerate_id(): Cannot regenerate session id - headers already sent (/var/www/yii/framework/web/CHttpSession.php:182)
Stack trace:
#0 /var/www/yii/framework/web/auth/CWebUser.php(228): CWebUser->changeIdentity()
#1 /var/www/taller/protected/models/LoginForm.php(71): CWebUser->login()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->login()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/models/LoginForm.php (71)
in /var/www/taller/protected/controllers/SiteController.php (88)
in /var/www/taller/index.php (13)
2012/06/08 23:46:17 [error] [exception.CException] exception 'CException' with message 'Propiedad "User"."alias" no se encuentra definida.' in /var/www/yii/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(144): CComponent->__get('alias')
#1 /var/www/taller/protected/components/UserIdentity.php(44): CActiveRecord->__get('alias')
#2 /var/www/taller/protected/components/UserIdentity.php(35): UserIdentity->getDatos(Object(User))
#3 /var/www/taller/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#5 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /var/www/yii/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#7 /var/www/taller/protected/controllers/SiteController.php(88): CModel->validate()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#9 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('login')
#13 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/login')
#14 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/taller/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/taller/index.php?r=site/login
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/08 23:50:52 [error] [php] session_regenerate_id(): Cannot regenerate session id - headers already sent (/var/www/yii/framework/web/CHttpSession.php:182)
Stack trace:
#0 /var/www/yii/framework/web/auth/CWebUser.php(228): CWebUser->changeIdentity()
#1 /var/www/taller/protected/models/LoginForm.php(71): CWebUser->login()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->login()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/models/LoginForm.php (71)
in /var/www/taller/protected/controllers/SiteController.php (88)
in /var/www/taller/index.php (13)
2012/06/08 23:51:46 [error] [php] session_regenerate_id(): Cannot regenerate session id - headers already sent (/var/www/yii/framework/web/CHttpSession.php:182)
Stack trace:
#0 /var/www/yii/framework/web/auth/CWebUser.php(228): CWebUser->changeIdentity()
#1 /var/www/taller/protected/models/LoginForm.php(71): CWebUser->login()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->login()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/models/LoginForm.php (71)
in /var/www/taller/protected/controllers/SiteController.php (88)
in /var/www/taller/index.php (13)
2012/06/08 23:53:13 [error] [exception.CException] exception 'CException' with message 'Propiedad "User"."relations" no se encuentra definida.' in /var/www/yii/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(144): CComponent->__get('relations')
#1 /var/www/taller/protected/components/UserIdentity.php(44): CActiveRecord->__get('relations')
#2 /var/www/taller/protected/components/UserIdentity.php(35): UserIdentity->getDatos(Object(User))
#3 /var/www/taller/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#5 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /var/www/yii/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#7 /var/www/taller/protected/controllers/SiteController.php(88): CModel->validate()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#9 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('login')
#13 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/login')
#14 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/taller/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/taller/index.php?r=site/login
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/08 23:53:18 [error] [exception.CException] exception 'CException' with message 'Propiedad "User"."relation" no se encuentra definida.' in /var/www/yii/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(144): CComponent->__get('relation')
#1 /var/www/taller/protected/components/UserIdentity.php(44): CActiveRecord->__get('relation')
#2 /var/www/taller/protected/components/UserIdentity.php(35): UserIdentity->getDatos(Object(User))
#3 /var/www/taller/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#5 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /var/www/yii/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#7 /var/www/taller/protected/controllers/SiteController.php(88): CModel->validate()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#9 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('login')
#13 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/login')
#14 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/taller/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/taller/index.php?r=site/login
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/08 23:53:25 [error] [php] session_regenerate_id(): Cannot regenerate session id - headers already sent (/var/www/yii/framework/web/CHttpSession.php:182)
Stack trace:
#0 /var/www/yii/framework/web/auth/CWebUser.php(228): CWebUser->changeIdentity()
#1 /var/www/taller/protected/models/LoginForm.php(71): CWebUser->login()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->login()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/models/LoginForm.php (71)
in /var/www/taller/protected/controllers/SiteController.php (88)
in /var/www/taller/index.php (13)
2012/06/08 23:54:40 [error] [exception.CException] exception 'CException' with message 'Propiedad "User"."relations" no se encuentra definida.' in /var/www/yii/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(144): CComponent->__get('relations')
#1 /var/www/taller/protected/components/UserIdentity.php(44): CActiveRecord->__get('relations')
#2 /var/www/taller/protected/components/UserIdentity.php(35): UserIdentity->getDatos(Object(User))
#3 /var/www/taller/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#5 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /var/www/yii/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#7 /var/www/taller/protected/controllers/SiteController.php(88): CModel->validate()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#9 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('login')
#13 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/login')
#14 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /var/www/taller/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/taller/index.php?r=site/login
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/08 23:55:02 [error] [exception.CException] exception 'CException' with message 'Propiedad "User"."relations" no se encuentra definida.' in /var/www/yii/framework/base/CComponent.php:131
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(144): CComponent->__get('relations')
#1 /var/www/yii/framework/base/CModel.php(593): CActiveRecord->__get('relations')
#2 /var/www/taller/protected/components/UserIdentity.php(44): CModel->offsetGet('relations')
#3 /var/www/taller/protected/components/UserIdentity.php(35): UserIdentity->getDatos(Object(User))
#4 /var/www/taller/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#5 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#6 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 /var/www/yii/framework/base/CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#8 /var/www/taller/protected/controllers/SiteController.php(88): CModel->validate()
#9 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#10 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#11 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#12 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('login')
#14 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/login')
#15 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /var/www/taller/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/taller/index.php?r=site/login
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/08 23:55:12 [error] [php] session_regenerate_id(): Cannot regenerate session id - headers already sent (/var/www/yii/framework/web/CHttpSession.php:182)
Stack trace:
#0 /var/www/yii/framework/web/auth/CWebUser.php(228): CWebUser->changeIdentity()
#1 /var/www/taller/protected/models/LoginForm.php(71): CWebUser->login()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->login()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/models/LoginForm.php (71)
in /var/www/taller/protected/controllers/SiteController.php (88)
in /var/www/taller/index.php (13)
2012/06/08 23:55:51 [error] [php] session_regenerate_id(): Cannot regenerate session id - headers already sent (/var/www/yii/framework/web/CHttpSession.php:182)
Stack trace:
#0 /var/www/yii/framework/web/auth/CWebUser.php(228): CWebUser->changeIdentity()
#1 /var/www/taller/protected/models/LoginForm.php(71): CWebUser->login()
#2 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->login()
#3 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#4 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#5 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#6 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#7 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/models/LoginForm.php (71)
in /var/www/taller/protected/controllers/SiteController.php (88)
in /var/www/taller/index.php (13)
2012/06/08 23:57:34 [error] [php] print_r() expects at least 1 parameter, 0 given (/var/www/taller/protected/components/UserIdentity.php:46)
Stack trace:
#0 /var/www/taller/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#1 /var/www/yii/framework/validators/CInlineValidator.php(43): LoginForm->authenticate()
#2 /var/www/yii/framework/validators/CValidator.php(197): CInlineValidator->validateAttribute()
#3 /var/www/yii/framework/base/CModel.php(158): CInlineValidator->validate()
#4 /var/www/taller/protected/controllers/SiteController.php(88): LoginForm->validate()
#5 /var/www/yii/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#6 /var/www/yii/framework/web/CController.php(309): CInlineAction->runWithParams()
#7 /var/www/yii/framework/web/CController.php(287): SiteController->runAction()
#8 /var/www/yii/framework/web/CController.php(266): SiteController->runActionWithFilters()
#9 /var/www/yii/framework/web/CWebApplication.php(276): SiteController->run()
#10 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController()
#11 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#12 /var/www/taller/index.php(13): CWebApplication->run()
REQUEST_URI=/taller/index.php?r=site/login
in /var/www/taller/protected/components/UserIdentity.php (46)
in /var/www/taller/protected/components/UserIdentity.php (35)
in /var/www/taller/protected/models/LoginForm.php (52)
2012/06/09 17:07:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php
---
2012/06/09 18:20:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php?r=site/login
---
2012/06/09 18:20:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in /var/www/yii/framework/web/actions/CViewAction.php:113
Stack trace:
#0 /var/www/yii/framework/web/actions/CViewAction.php(124): CViewAction->resolveView('Demo 404 page')
#1 /var/www/yii/framework/web/actions/CAction.php(75): CViewAction->run()
#2 /var/www/yii/framework/web/CController.php(309): CAction->runWithParams(Array)
#3 /var/www/yii/framework/web/CController.php(287): CController->runAction(Object(CViewAction))
#4 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('page')
#6 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('site/page')
#7 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /var/www/taller/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/taller/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/taller/index.php?r=site/index
---
2012/06/09 18:21:04 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /var/www/yii/framework/web/auth/CAccessControlFilter.php:157
Stack trace:
#0 /var/www/yii/framework/web/auth/CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /var/www/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /var/www/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('admin')
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('phone/admin')
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/taller/index.php?r=phone/admin
HTTP_REFERER=http://localhost/taller/index.php?r=phone
---
2012/06/09 18:21:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /var/www/yii/framework/web/auth/CAccessControlFilter.php:157
Stack trace:
#0 /var/www/yii/framework/web/auth/CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /var/www/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /var/www/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('admin')
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('person/admin')
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/taller/index.php?r=person/admin
---
2012/06/09 18:21:25 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /var/www/yii/framework/web/auth/CAccessControlFilter.php:157
Stack trace:
#0 /var/www/yii/framework/web/auth/CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /var/www/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/yii/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /var/www/yii/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/yii/framework/web/CController.php(292): CFilterChain->run()
#6 /var/www/yii/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii/framework/web/CWebApplication.php(276): CController->run('admin')
#8 /var/www/yii/framework/web/CWebApplication.php(135): CWebApplication->runController('person/admin')
#9 /var/www/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /var/www/taller/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/taller/index.php?r=person/admin
HTTP_REFERER=http://localhost/taller/index.php?r=person/
---
